INSERT INTO tb_category (name, created_at) VALUES ('Livros', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Eletrônicos', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Computadores', NOW());
INSERT INTO tb_category (name, created_at) values('Material de Limpeza', NOW());
INSERT INTO tb_category (name, created_at) values('Matereial de escritório', NOW());
INSERT INTO tb_category (name, created_at) values('EPI', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Livros', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Eletrônicos', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Computadores', NOW());
INSERT INTO tb_category (name, created_at) values('Material de Limpeza', NOW());
INSERT INTO tb_category (name, created_at) values('Matereial de escritório', NOW());
INSERT INTO tb_category (name, created_at) values('EPI', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Livros', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Eletrônicos', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Computadores', NOW());
INSERT INTO tb_category (name, created_at) values('Material de Limpeza', NOW());
INSERT INTO tb_category (name, created_at) values('Matereial de escritório', NOW());
INSERT INTO tb_category (name, created_at) values('EPI', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Livros', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Eletrônicos', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Computadores', NOW());
INSERT INTO tb_category (name, created_at) values('Material de Limpeza', NOW());
INSERT INTO tb_category (name, created_at) values('Matereial de escritório', NOW());
INSERT INTO tb_category (name, created_at) values('EPI', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Livros', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Eletrônicos', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Computadores', NOW());
INSERT INTO tb_category (name, created_at) values('Material de Limpeza', NOW());
INSERT INTO tb_category (name, created_at) values('Matereial de escritório', NOW());
INSERT INTO tb_category (name, created_at) values('EPI', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Livros', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Eletrônicos', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Computadores', NOW());
INSERT INTO tb_category (name, created_at) values('Material de Limpeza', NOW());
INSERT INTO tb_category (name, created_at) values('Matereial de escritório', NOW());
INSERT INTO tb_category (name, created_at) values('EPI', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Livros', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Eletrônicos', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Computadores', NOW());
INSERT INTO tb_category (name, created_at) values('Material de Limpeza', NOW());
INSERT INTO tb_category (name, created_at) values('Matereial de escritório', NOW());
INSERT INTO tb_category (name, created_at) values('EPI', NOW());